spring:
  application:
    name: ms-vehicle
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate.default_schema: vehicle
    hibernate:
      ddl-auto: none

server:
  port: ${APP_PORT}

springdoc:
  swagger-ui:
    path: /index.html
    enabled: false
  api-docs:
    enabled: false
    path: /v3/api-docs