spring:
  application:
    name: ${APP_NAME}
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${HOST}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    default-schema: vehicle
    liquibase-schema: vehicle
    database-change-log-lock-table: vehicle_changelog_lock
    database-change-log-table: vehicle_changelog
  jpa:
    properties:
      hibernate.default_schema: vehicle
    hibernate:
      ddl-auto: none

server:
  port: ${APP_PORT}

springdoc:
  swagger-ui:
    path: /index.html
    enabled: ${SHOW_SWAGGER}
  api-docs:
    enabled: ${SHOW_SWAGGER}
    path: /v3/api-docs