apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-vehicle-deployment
  namespace: default
  labels:
    app: ms-vehicle
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-vehicle
  template:
    metadata:
      labels:
        app: ms-vehicle
    spec:
      containers:
        - name: ms-vehicle
          image: finthos/ms-vehicle:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ms-vehicle-config
            - secretRef:
                name: ms-vehicle-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
