apiVersion: v1
kind: Service
metadata:
  name: ms-vehicle-service
  namespace: default
spec:
  selector:
    app: ms-vehicle
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30002
  type: NodePort

